/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.InformeFrames;


import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author johann
 */
public class JFLproductos extends javax.swing.JFrame {

    BD.ConexionBD cc = new BD.ConexionBD();
    BD.botonesEstilosos btnStyle = new BD.botonesEstilosos();
    BD.ParametrosTexto pt = new BD.ParametrosTexto();
    
    String llenarubros="SELECT nom_rubro FROM tb_rubros";
    String llenamarcas="SELECT nom_marca FROM tb_marcas";
    String llenaunidades="SELECT nom_unidad FROM tb_unidades";
    String llenaprov="SELECT nomproveedor FROM tb_proveedor";
    
    public JFLproductos() {
        initComponents();
        pt.seteaFrame(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rbmarca = new javax.swing.JRadioButton();
        cbxTipoI = new javax.swing.JComboBox<>();
        rbrubro = new javax.swing.JRadioButton();
        rbsmin = new javax.swing.JRadioButton();
        rbuni = new javax.swing.JRadioButton();
        rbprov = new javax.swing.JRadioButton();
        rball = new javax.swing.JRadioButton();
        btnGenerate = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pt.seteaPanel(jPanel1);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Seleccione Informe"));

        buttonGroup1.add(rbmarca);
        rbmarca.setText("Por Marca");
        rbmarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbmarcaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbrubro);
        rbrubro.setText("Por Rubro");
        rbrubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbrubroActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbsmin);
        rbsmin.setText("Stock Mínimo");
        rbsmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbsminActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbuni);
        rbuni.setText("Por Unidad");
        rbuni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbuniActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbprov);
        rbprov.setText("Por Proveedor");
        rbprov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbprovActionPerformed(evt);
            }
        });

        buttonGroup1.add(rball);
        rball.setSelected(true);
        rball.setText("Todos");
        rball.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rballActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbrubro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(rball)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbmarca)
                            .addComponent(rbsmin)
                            .addComponent(rbprov))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbuni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbxTipoI, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbrubro)
                    .addComponent(rball))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbmarca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbuni)
                    .addComponent(cbxTipoI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbsmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbprov)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnGenerate.setText("Generar");
        btnStyle.btnImprimir(btnGenerate, "Generar", "Generar Documento");
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });

        btnexit.setText("Salir");
        btnStyle.btnImprimir(btnexit, "Salir", "");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnexit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnexit, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbmarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmarcaActionPerformed
        try{
            cbxTipoI.setVisible(true);
            cc.cargacombobox(llenamarcas, cbxTipoI, cc.conectar());
            cc.conectar().close();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_rbmarcaActionPerformed

    private void rbrubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbrubroActionPerformed
        try{
            cbxTipoI.setVisible(true);
            cc.cargacombobox(llenarubros, cbxTipoI, cc.conectar());
            cc.conectar().close();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }//GEN-LAST:event_rbrubroActionPerformed

    private void rbsminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbsminActionPerformed
        cbxTipoI.setVisible(false);

    }//GEN-LAST:event_rbsminActionPerformed

    private void rbuniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbuniActionPerformed
        try{
            cbxTipoI.setVisible(true);
            cc.cargacombobox(llenaunidades, cbxTipoI, cc.conectar());
            cc.conectar().close();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_rbuniActionPerformed

    private void rbprovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbprovActionPerformed
        cbxTipoI.setVisible(true);
        try{
            cc.cargacombobox(llenaprov, cbxTipoI, cc.conectar());
            cc.conectar().close();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_rbprovActionPerformed

    private void rballActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rballActionPerformed
        cbxTipoI.setVisible(false);
    }//GEN-LAST:event_rballActionPerformed

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        if((rbrubro.isSelected()&& cbxTipoI.getSelectedIndex()>0) || (rbmarca.isSelected()&& cbxTipoI.getSelectedIndex()>0)
                ||(rbuni.isSelected() && cbxTipoI.getSelectedIndex()>0) || (rbprov.isSelected() && cbxTipoI.getSelectedIndex()>0)
                ||(this.rbsmin.isSelected())||(this.rball.isSelected())){
            JasperReport jr = null;
            String path="/GUI/Informes/Productos/JRprod.jasper";
            Map parametro =  new HashMap();        
            if(rbrubro.isSelected()){
                String seleccionado=cbxTipoI.getSelectedItem().toString().toLowerCase();
                parametro.put("parameter1", "WHERE rubro='"+cbxTipoI.getSelectedItem()+"'");                
                parametro.put("parameter2", "Ordenados "+rbrubro.getText());
                if(seleccionado.equals("semillas")||seleccionado.equals("semilla")){
                    path="/GUI/Informes/Productos/JRsemilla.jasper";
                    parametro.put("parameter1", "AND rubro='"+cbxTipoI.getSelectedItem()+"'");
                }                
            }else if(rbmarca.isSelected()){
                parametro.put("parameter1", "WHERE marca='"+cbxTipoI.getSelectedItem()+"'");
                parametro.put("parameter2", "Ordenados "+rbmarca.getText());
            }else if(rbuni.isSelected()){
                parametro.put("parameter1", "WHERE unidad='"+cbxTipoI.getSelectedItem()+"'");
                parametro.put("parameter2", "Ordenados "+rbuni.getText());
            }else if(rbsmin.isSelected()){
                parametro.put("parameter1", "WHERE stock <= stockmin ");
                parametro.put("parameter2", "Ordenados "+rbsmin.getText());
            }else if(rbprov.isSelected()){
                parametro.put("parameter1", "WHERE proveedor='"+cbxTipoI.getSelectedItem()+"'");
                parametro.put("parameter2", "Ordenados "+rbprov.getText());
            }else if(rball.isSelected()){
                parametro.put("parameter1", "");
                parametro.put("parameter2", "Inventario Completo ");
            }
            try {
                jr = (JasperReport) JRLoader.loadObject(getClass().getResource(path));
                JasperPrint jp = JasperFillManager.fillReport(jr, parametro, cc.conectar());

                JasperViewer jv = new JasperViewer(jp, false);
                jv.setVisible(true);
                jv.toFront();
                jv.setTitle("Reporte de productos");
                cc.conectar().close();
            } catch (JRException | SQLException ex ) {
                JOptionPane.showMessageDialog(this, ex.getMessage());

            }
        }else{
            JOptionPane.showMessageDialog(this,"Debe al menos seleccionar una opcion");
        } 
    }//GEN-LAST:event_btnGenerateActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnexitActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        this.cbxTipoI.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFLproductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFLproductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFLproductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFLproductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFLproductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerate;
    private javax.swing.JButton btnexit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxTipoI;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rball;
    private javax.swing.JRadioButton rbmarca;
    private javax.swing.JRadioButton rbprov;
    private javax.swing.JRadioButton rbrubro;
    private javax.swing.JRadioButton rbsmin;
    private javax.swing.JRadioButton rbuni;
    // End of variables declaration//GEN-END:variables
}
