/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Ventas;

import BD.Toast;
import static GUI.MainForm.cargo;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author johann
 */
public class JFBuscaVentas extends javax.swing.JFrame {
    
    BD.ConexionBD cc= new BD.ConexionBD();
    BD.botonesEstilosos btnStyle = new BD.botonesEstilosos();
    BD.ParametrosTexto pt = new BD.ParametrosTexto(); 
    
    String fila[][];    
    String Fillventa="SELECT n_boleta, fechaventa, cliente, usuario, medio_pago, subtotal, descuento, totalventa FROM tb_venta WHERE nulo=0"; 
    String Fillanula="SELECT n_boleta, fechaventa, cliente, usuario, medio_pago, subtotal, descuento, totalventa FROM tb_venta WHERE nulo=1";
    
    String coldet[]={"Codigo", "Cantidad", "Detalle", "Precio", "Monto"};
    String colven[]={"N° Boleta","Fecha de Venta","Cliente","Usuario","Medio de Pago","Subtotal","Descuento","Total"};
    
    
    
    
    DefaultTableModel venta = new DefaultTableModel(fila,colven){
        public boolean isCellEditable(int fila, int col){
            return false;
        }
    };
    DefaultTableModel content = new DefaultTableModel(fila,coldet){
      public boolean isCellEditable(int fila, int col){
          return false;
      }
    };
    DefaultTableModel anuladas = new DefaultTableModel(fila,colven){
      public boolean isCellEditable(int fila, int col){
          return false;
      }
    };
    DefaultTableModel detalle = new DefaultTableModel(fila,coldet){
      public boolean isCellEditable(int fila, int col){
          return false;
      }
    };
    
    public JFBuscaVentas() {
        initComponents();
        btnStyle.btnAnular(jButton2, "Anular", "Anula un venta");
        btnStyle.btnBuscar(jButton7, "", "Busca una venta");
        btnStyle.btnSalir(jButton4,"Salir","SALIR");
        btnStyle.btnSalir(jButton3,"Salir","SALIR");
    }
    public void activacontrol()
        {
            if (cargo.equals("Administrador"))
            {
                jButton2.setVisible(true);
            }else if(cargo.equals("Bodega"))
            {
                jButton2.setVisible(false);
            }else if(cargo.equals("Otro"))
            {
                jButton2.setVisible(false);
            }
        }   
    public void cargadoble(String tb1, String tb2,JTable tabla, DefaultTableModel model){
        String[] datos = new String[5];
        for (int j = 0; j < 2; j++){
            switch(j){
                case 0:
                try {
                    Statement st = cc.conectar().createStatement();
                    ResultSet rs = st.executeQuery(tb1);
                    while(rs.next()){
                        for (int i = 0; i < 5; i++) {
                            datos[i] = rs.getString(i+1);
                        }
                        model.addRow(datos);
                    }
                    tabla.setModel(model);

                }catch(SQLException e){
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
                break;
                case 1:
                try {
                    Statement st = cc.conectar().createStatement();
                    ResultSet rs = st.executeQuery(tb2);
                    while(rs.next()){
                        for (int i = 0; i < 5; i++) {
                            datos[i] = rs.getString(i+1);
                        }
                        model.addRow(datos);
                    }
                    tabla.setModel(model);

                }catch(SQLException e){
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
                break;
            }

        }
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProductos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbventahecha = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbAnuladas = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbDetalle = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(661, 510));
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(661, 550));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        pt.seteaPanel(jPanel3);
        jPanel3.setPreferredSize(new java.awt.Dimension(558, 550));

        pt.seteaPanel(jPanel4);
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Contenidos de Venta"));
        jPanel4.setEnabled(false);

        pt.seteaTabla(tbProductos);
        tbProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbProductos);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addContainerGap())
        );

        pt.seteaTabla(tbventahecha);
        tbventahecha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbventahecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbventahechaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbventahecha);

        jButton2.setText("Anular");
        btnStyle.btnAnular(jButton2,"Anular","Anular Venta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Salir");
        btnStyle.btnSalir(jButton3,"Salir","");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnStyle.btnBuscar(jButton7,"","Buscar Ventas");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Ventas Realizadas", jPanel3);

        pt.seteaPanel(jPanel5);

        pt.seteaTabla(tbAnuladas);
        tbAnuladas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbAnuladas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAnuladasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbAnuladas);

        pt.seteaPanel(jPanel6);
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Contenidos de la Venta"));
        jPanel6.setEnabled(false);

        pt.seteaTabla(tbDetalle);
        tbDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tbDetalle);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton4.setText("Salir");
        btnStyle.btnSalir(jButton4,"Salir","");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );

        jTabbedPane1.addTab("Ventas Anuladas", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     
        activacontrol();       
        tbventahecha.setAutoCreateRowSorter(true);
        tbAnuladas.setAutoCreateRowSorter(true);        
        tbventahecha.setModel(venta);  
        tbProductos.setModel(content); 
        tbAnuladas.setModel(anuladas);
        tbDetalle.setModel(detalle);
        try{
        cc.cargatabla(Fillventa, 8, venta, tbventahecha, cc.conectar());
        cc.conectar().close();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
        
    }//GEN-LAST:event_formWindowOpened

    private void tbAnuladasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAnuladasMouseClicked
             try{
                int filasel= tbAnuladas.getSelectedRow();
                detalle.setRowCount(0);
                String llenaProd="SELECT codprod, cantidad, producto, precio_unitario, precio_total"
                + " FROM tb_ventaprod"
                + " WHERE n_bol="+tbAnuladas.getValueAt(filasel, 0)+"";

                String llenaPack="SELECT codpack, cantidad, nombrepack, precio_unitario, precio_total"
                + " FROM tb_ventapack"
                + " WHERE n_bol="+tbAnuladas.getValueAt(filasel, 0)+"";
                cargadoble(llenaProd, llenaPack, tbDetalle,detalle);
                cc.conectar().close();
             }catch(SQLException ex){
                 JOptionPane.showMessageDialog(this, ex.getMessage());
             }
    }//GEN-LAST:event_tbAnuladasMouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        try{
        cc.cargatabla(Fillanula, 8, anuladas, tbAnuladas, cc.conectar());
        cc.conectar().close();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            cc.cargatabla(Fillventa, 8, venta, tbventahecha, cc.conectar());
            cc.conectar().close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());        
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            int resp = JOptionPane.showConfirmDialog(null, "¿Está seguro de que desea anular esta venta?\n No podrá recuperarla una vez que la anule", "Alerta!", JOptionPane.YES_NO_OPTION);
            
            if (resp == JOptionPane.YES_OPTION) {
                int filasel = tbventahecha.getSelectedRow();
                int filas = this.tbProductos.getRowCount();
                String anula = "UPDATE tb_venta SET nulo = 1 WHERE n_boleta=" + tbventahecha.getValueAt(filasel, 0) + "";                
                cc.Insert(anula);
                
                for (int i = 0; i < filas ; i++) {                    
                    String cod = this.tbProductos.getValueAt(i, 0).toString();
                    int stock = Integer.parseInt(this.tbProductos.getValueAt(i, 1).toString());
                    String stockup = "UPDATE tb_productos SET stock = stock+"+stock+" WHERE codprod = '"+cod+"'";
                    cc.Insert(stockup);
                }
                cc.cargatabla(this.Fillventa, 8, venta, tbventahecha, cc.conectar());
                cc.conectar().close();
                BD.Toast.makeText(JFBuscaVentas.this, "Venta Anulada con exito!", Toast.Style.SUCCESS).display();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tbventahechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbventahechaMouseClicked
        // TODO add your handling code here:
        int filasel= tbventahecha.getSelectedRow();
        content.setRowCount(0);
        String llenaProd="SELECT codprod, cantidad, producto, precio_unitario, precio_total"
        + " FROM tb_ventaprod"
        + " WHERE n_bol="+tbventahecha.getValueAt(filasel, 0)+"";

        String llenaPack="SELECT codpack, cantidad, nombrepack, precio_unitario, precio_total"
        + " FROM tb_ventapack"
        + " WHERE n_bol="+tbventahecha.getValueAt(filasel, 0)+"";
        
        cargadoble(llenaProd, llenaPack,tbProductos,content);
        
    }//GEN-LAST:event_tbventahechaMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:
        activacontrol();
    }//GEN-LAST:event_formWindowStateChanged
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFBuscaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JFBuscaVentas().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbAnuladas;
    private javax.swing.JTable tbDetalle;
    private javax.swing.JTable tbProductos;
    private javax.swing.JTable tbventahecha;
    // End of variables declaration//GEN-END:variables
}
